---
- name: Create and run a Docker container using a custom image
  hosts: dev 
  become: true 
  
  tasks:
    - name: Install Python pip3
      apt:
        name: python-pip3
        state: present
    - name: Install docker-py python module
      pip3:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: myansible01
        image: "hellosahebpm/mywebapp:0.0.6"
        state: started
        published_ports:
          - 0.0.0.0:80:80
      
